Good textboxes, closes #23
liquidev/netcanv pull request #34
Opened 2021-09-15 16:51 UTC by Firstbober

Good textboxes.

2021-09-15 17:09 UTC, liquidev reviewed
Overall I can't say I'm too fond of this implementation. Having worked with text fields myself some, I can say that your implementation with this `selection_cursor_pos` thing is quite sub-optimal and leads to quite a few edge cases that have to be ironed out explicitly (see review comments for a better solution).

I don't want to be rude here, but I think it would be better if a person experienced in writing text fields (or text editors) would do this.

2021-09-15 17:09 UTC, liquidev commented on src/ui/input.rs
> +    key_down: [bool; KEY_CODE_COUNT],
To follow the conventions already established with `mouse_button_is_down`, please rename this field to `key_is_down`.

2021-09-15 17:09 UTC, liquidev commented on src/ui/input.rs
> +    pub fn key_down(&self, key: VirtualKeyCode) -> bool {
Similarly, this function should be renamed to `key_is_down`.

2021-09-15 17:09 UTC, liquidev commented on src/ui/textfield.rs
> +    selection_cursor_pos: usize,
Avoid using shortcut names like `pos`. Prefer `position` instead.

2021-09-15 17:09 UTC, liquidev commented on src/ui/textfield.rs
> +    clipboad_context: ClipboardContext,
This field's name has a typo, `clipbo`**`ad`** instead of `clipbo`**`ard`**.

2021-09-15 17:09 UTC, liquidev commented on src/ui/textfield.rs
> +                let curr_text: String = self.text[..self.cursor_pos].iter().collect();
Collecting the slice into a String is quite inefficient, as you're allocating a new String each frame, thus fragmenting the heap a lot. Instead, borrow the char slice using `&self.text[..self.cursor_pos]`.

However, I have also noticed that you're probably doing this because `measure_str` expects a `&str` instead of a `&[char]`. So I guess this can stay as a temporary solution until we have better, more abstract render backends available.

2021-09-15 17:09 UTC, liquidev commented on src/ui/textfield.rs
> +                let pre_selection_text: String = self.text[..self.selection_cursor_pos].iter().collect();
As far as I could tell, this system of yours assumes that the selection is always made from left to right, which isn't always the case. A better solution would be to store `start` and `end` cursors. It makes a lot of the math easier and would probably work better with all the string slicing shenanigans that are needed to obtain `&str`s from the text field's text (see the `text_utf8` field of `struct TextField`).

2021-09-15 17:09 UTC, liquidev commented on src/ui/textfield.rs
> +                let sel_text_width = if self.cursor_pos < self.selection_cursor_pos {
Again, avoid truncating words in identifiers. `sel` should be `selection`.

2021-09-15 20:40 UTC, liquidev requested changes
I'm quite happy with the changes you've made, but there are still some tweaks I'd want you to make before this is merged.

As for documenting the functions, I'll take care of that myself after this is merged, so you shouldn't stress it too much.

2021-09-15 20:40 UTC, liquidev commented on .github/workflows/build.yaml
> +      run: sudo apt-gen install -y libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev
I think there's a typo here, it should be `apt-get`, not `apt-gen`.

2021-09-15 20:40 UTC, liquidev commented on src/ui/textfield.rs
> +/// Text field selection struct
I think this comment could be a bit more descriptive. Maybe try

> Text field selection.
> 
> This stores two cursors: the selection anchor, and the actual text cursor.
These cursors are modified appropriately as the user edits text.

2021-09-15 20:40 UTC, liquidev commented on src/ui/textfield.rs
> +    pub second: usize,
I think the names of these fields could better summarize what they're for; maybe `first` → `cursor`, and `second` → `anchor`? Then they could also use some doc comments, like:
```rs
/// The actual text cursor as moved by the user, shown as a black (or white) beam in the text.
cursor: usize,
/// The "selection anchor". This is where the selection is anchored at.
/// This anchor normally moves together with the cursor, but becomes detached once the user presses Shift.
anchor: usize,
```
Also, the fields don't need to be public as `struct Selection` is private to the textfield module.

2021-09-15 20:40 UTC, liquidev commented on src/ui/textfield.rs
> +            },
Using the UTF-8 length here is incorrect! Note that the selection positions are expressed using indices into the `text` table, whose length may be shorter than that of `text_utf8`.

As a note for the future, `text_utf8` is only used as a buffer for using the text in modules outside this one, as pretty much noone in Rust-land speaks `&[char]` for strings, however they do speak `&str`.

2021-09-15 20:40 UTC, liquidev commented on src/ui/textfield.rs
> +                // Get text left to right or right to left depending on end cursor position.
This comment is a bit outdated and describes behavior from an older revision of this PR. Right now this code doesn't care about relative positioning of the cursor vs the anchor, as that's done by `Selection::normalize()`.

2021-09-15 20:40 UTC, liquidev commented on src/ui/textfield.rs
> +    fn handle_word_skipping_and_selection(
Generally NetCanv's codebase uses the word `process` for processing input and UI layout, rather than `handle`.

2021-09-15 20:40 UTC, liquidev commented on src/ui/textfield.rs
> +    pub fn move_cursors(&mut self, position: usize) {
I think a better name for this function would be `move_to`, `move_cursors` implies there are multiple cursors here but in reality there's just one, plus the anchor.

2021-09-15 20:40 UTC, liquidev commented on src/ui/textfield.rs
> +}
Similarly these should be named `move_left` and `move_right`. Also, try hoisting the moving-while-Shift-is-down logic into these functions by adding a `shift: bool` parameter that will disable setting `self.second` to `self.first`.

2021-09-15 20:41 UTC, liquidev commented on .github/workflows/build.yaml
> +      run: sudo apt-gen install -y libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev
Outdated, I forgot to remove the review comment.

2021-09-16 14:21 UTC, liquidev commented on src/ui/textfield.rs
> +                // Get text selected text
There's still a minor typo in this comment, I think it should say "Get selected text".

2021-09-16 14:25 UTC, liquidev approved these changes

2021-09-16 14:26 UTC, liquidev commented
All looking good now. I'll check how well it works later, and then merge the changes.

2021-09-16 17:38 UTC, liquidev commented
Okay, I noticed some more problems while testing.

First of all, you seem to be drawing the selection _over_ the text instead of _under_, which causes poor contrast on dark mode.
![image](https://user-images.githubusercontent.com/16415678/133658452-47f9fb71-f14c-4a29-a8ca-08f69e6dfaf4.png)
It would also cause the text to be tinted if the selection color is, well, a color, instead of just grayscale.

Second, it seems that Ctrl+Left/Right only skip until they hit the first whitespace character. They don't skip continuous spans of spaces, which isn't how usual text boxes behave.

Third, selection is retained when a textbox is unfocused, which leads to this:
![image](https://user-images.githubusercontent.com/16415678/133658677-492c212c-457d-4e19-9ca6-ed4fb61a28da.png)
Instead, the anchor should be merged with the cursor position.

Missing keyboard shortcuts:
- Ctrl+Backspace
- Ctrl+Delete
- Shift+Tab, to focus the previous text box. This should be implemented in `ui::chain_focus`.

2021-09-18 22:17 UTC, liquidev commented on src/ui/textfield.rs
> +            println!("{}", ix);
You seem to have left a debug println in your code.

2021-09-18 22:17 UTC, liquidev commented on src/ui/textfield.rs
> +    ) {
I'm not too fond of the fact you have two `bool` parameters here. It's quite easy to confuse them. I'd hoist the `right` parameter to an `enum ArrowKey { Left, Right }`.

I'm also not sure what `not_found_ws_value`'s purpose is. Maybe you choose a more self-explanatory name, or leave a comment explaining what it is?

2021-09-18 22:18 UTC, liquidev commented
Also, Shift+Tab seems to be broken as it doesn't wrap around to the last text box when the first text box is focused.

2021-09-19 13:24 UTC, Firstbober commented
Fixed.

2021-09-19 13:35 UTC, liquidev commented
I just noticed Shift+Home and Shift+End are missing as well, but we can add that after this is merged.

2021-09-19 13:35 UTC, merged